#!/usr/bin/env python3.10
import logging

from libnext.backend import NextCore

if __name__ == "__main__":
    log = logging.getLogger("NextWM")
    logging.basicConfig(
        level=logging.DEBUG,
        format="(%(asctime)s) %(levelname)s %(message)s",
        datefmt="%d/%m/%y - %H:%M:%S %Z"
    )
    # TODO: colored logs.
    NextCore()
