next(1) "github.com/shinyzenith/nextwm" "General Commands Manual"

# NAME

NextWM - Wayland compositing window manager.

# SYNOPSIS

*next* [_flags_]

# DESCRIPTION

*NextWM* is a wayland compositing window manager written in python.

# OPTIONS

*-h*
	Print the help message and exit.

*-d*
	Enable debug mode.

# AUTHORS

Maintained by Shinyzenith <aakashsensharma@gmail.com>.
For more information about development, see <https://github.com/shinyzenith/nextwmm>.
