#!/usr/bin/env python3
# Copyright (c) 2022 Shinyzenith <aakashsensharma@gmail.com>
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice,
# this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright
# notice, this list of conditions and the following disclaimer in the
# documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
# FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
# COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
# NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
# OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
# EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

import argparse
import logging
import os

import wlroots

from libnext.backend import NextCore


def main():
    # Default log level.
    log_level = logging.ERROR
    wlroots.util.log.log_init(log_level)

    # Setting up the parser.
    parser = argparse.ArgumentParser(description="NextWM - Wayland compositing window manager.")
    parser.add_argument("-d", "--debug", help="enable debug mode", action="store_true")
    args = parser.parse_args()

    if args.debug:
        log_level = logging.DEBUG
        wlroots.util.log.log_init(log_level)

    log = logging.getLogger("NextWM")
    logging.basicConfig(
        level=log_level,
        format="(%(asctime)s) %(levelname)s %(message)s",
        datefmt="%d/%m/%y - %H:%M:%S %Z"
    )

    try:
        import coloredlogs
        if args.debug:
            coloredlogs.install(logger=log, level='DEBUG')
        else:
            coloredlogs.install(logger=log)
    finally:
        log.info(f"Starting NextWM with PID: {os.getpid()}")
        NextCore()


if __name__ == "__main__":
    main()
